Repository nltp-ashes/Western-Goods, pull requests merged in 2023-10, with the labels that each got.

#21 fix(inventory-lag): Inventory Lag Fix
  gamedata/scripts/western_goods_trade_eur_usd.script
  gamedata/scripts/western_goods_utils.script
Labels: bug, enhancement

#23 feature(class-members): LUA Class Members
  gamedata/scripts/western_goods_ui_gps_locator.script
  gamedata/scripts/western_goods_ui_rangefinder.script
  gamedata/scripts/western_goods_ui_readable.script
Labels: enhancement

#24 fix(gps-ui): GPS UI Fix
  gamedata/scripts/western_goods_ui_gps_locator.script
Labels: bug

#25 feature(items-cam-anims): Items Camera Animations
  CHANGELOG.md
  README.md
  gamedata/configs/plugins/mod_actor_effects_western_goods.ltx
Labels: enhancement

#26 Literally everything(somehow)
  gamedata/configs/text/rus/st_core_western_goods.xml
  gamedata/configs/text/rus/st_dialogs_western_goods.xml
  gamedata/configs/text/rus/st_encyclopedia_western_goods.xml
  gamedata/configs/text/rus/st_items_western_goods_drinks.xml
  gamedata/configs/text/rus/st_items_western_goods_food.xml
  gamedata/configs/text/rus/st_items_western_goods_mags.xml
  gamedata/configs/text/rus/st_items_western_goods_money.xml
  gamedata/configs/text/rus/st_items_western_goods_task.xml
  gamedata/configs/text/rus/st_items_western_goods_tech.xml
  gamedata/configs/text/rus/st_mcm_western_goods.xml
  gamedata/configs/text/rus/st_npcs_western_goods.xml
  gamedata/configs/text/rus/st_plugin_pinup_collect_western_goods.xml
  gamedata/configs/text/rus/st_task_western_goods.xml
Labels: enhancement
