Repository nltp-ashes/Western-Goods, pull requests merged in 2024-02, with the labels that each got.

#49 feature(mil-spec): Add Milspec To PDA List
  gamedata/scripts/western_goods_utils.script
Labels: fix

#50 feature(missing-squad): Add CTD On Missing Squad
  gamedata/scripts/western_goods_core.script
  gamedata/scripts/western_goods_utils.script
Labels: feature

#51 fix(dev-rangefinder): Fixed Rangefinder Zoom
  gamedata/configs/items/weapons/m_rangefinder.ltx
Labels: fix

#52 fix(mcm-rangefinder-nv): Fix Confusing MCM Rangefinder NV Mode
  gamedata/configs/text/eng/st_western_goods_mcm.xml
  gamedata/configs/text/rus/st_western_goods_mcm.xml
Labels: fix

#53 feature(dev-lighter-binder): Lighter Binder
  gamedata/configs/items/items/items_western_goods_tech.ltx
  gamedata/scripts/modxml_western_goods.script
  gamedata/scripts/western_goods_bind_fire_source.script
  gamedata/scripts/western_goods_bind_lighter.script
  gamedata/scripts/western_goods_bind_object.script
  gamedata/scripts/western_goods_core.script
  gamedata/scripts/western_goods_ui_lighter.script
Labels: fix, feature

#54 fix(dev-lighter): Lighter Fixes
  gamedata/scripts/western_goods_bind_fire_source.script
  gamedata/scripts/western_goods_bind_lighter.script
  gamedata/scripts/western_goods_bind_object.script
  gamedata/scripts/western_goods_monkey_patches.script
Labels: fix

#55 feature(monkey-patches): Port Monkey-Patches To New System
  gamedata/scripts/western_goods_loot.script
  gamedata/scripts/western_goods_monkey_patches.script
  gamedata/scripts/western_goods_trade_eur_usd.script
  gamedata/scripts/western_goods_ui_gps_locator.script
  gamedata/scripts/western_goods_ui_readable.script
Labels: feature

#56 fix(dev-lighter): Fix Lighter Fuel Level
  gamedata/scripts/western_goods_bind_lighter.script
Labels: fix

#59 fix(remove-compass-code): Remove Compass Code
  gamedata/scripts/western_goods_core.script
  gamedata/scripts/western_goods_mcm.script
Labels: fix

#61 feature(3d-uis-digits): 3D UI Digits
  gamedata/scripts/western_goods_ui_gps_locator.script
  gamedata/scripts/western_goods_ui_rangefinder.script
  gamedata/scripts/western_goods_utils.script
Labels: fix, feature
